# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 # Pods for project
  pod 'SwiftLint'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'
#  pod 'Firebase/Database'

  target 'projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
